# Pandas 学习笔记

## 第1章：Pandas基础

### 1.1 导入Pandas和NumPy

In [4]:
# 导入pandas并使用pd作为别名（约定俗成）
import pandas as pd
# 同时导入numpy，因为pandas底层依赖numpy
import numpy as np

### 1.2 Pandas数据结构 - Series

In [5]:
# Series是一维数组对象，包含数据和索引
# 从列表创建Series，默认索引是0,1,2,...
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
# 获取Series的值（返回numpy数组）
obj.values

array([ 4,  7, -5,  3])

In [7]:
# 获取Series的索引对象
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
# 创建带有自定义索引的Series
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
# 通过索引标签选择数据
obj2['a']

np.int64(-5)

In [10]:
# 通过索引标签赋值
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [11]:
# 同时选择多个索引
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
# 使用布尔条件过滤
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
# Series与标量运算
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
# 应用NumPy函数
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
# 可以将Series看作固定长度的有序字典
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
# 从Python字典创建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
# 传入索引列表，可以指定顺序，缺失值会用NaN填充
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
# 检查缺失值：isnull和notnull
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
# Series的实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
# Series自动对齐索引进行运算
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
# 相加时，索引对齐，不匹配的为NaN
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [24]:
# Series及其索引都有name属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [25]:
# 索引可以通过赋值就地修改
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 1.3 Pandas数据结构 - DataFrame

In [26]:
# DataFrame是表格型数据结构，包含行和列
# 从字典创建DataFrame，字典的键作为列名
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
# 显示前几行
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
# 指定列的顺序
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [29]:
# 传入不存在的列，会用NaN填充
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [30]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [31]:
# 通过字典标记或属性获取一列，返回Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [32]:
# 属性方式访问列（要求列名是有效的Python变量名）
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [33]:
# 通过loc属性选择行
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [34]:
# 给列赋值
frame2['debt'] = 16.5
frame2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [35]:
# 用数组或列表给列赋值
frame2['debt'] = np.arange(6.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [36]:
# 用Series给列赋值，会按索引对齐
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [37]:
# 创建新列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [38]:
# 删除列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
# 从嵌套字典创建DataFrame
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}
}
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [40]:
# DataFrame转置
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [41]:
# 指定索引
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [42]:
# 从Series字典创建DataFrame
pdata = {
    'Ohio': frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:2]
}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [43]:
# 设置DataFrame的name属性
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [44]:
# values属性以ndarray形式返回数据
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [45]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 1.4 索引对象

In [46]:
# Index对象是不可变的
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [47]:
index[1:]

Index(['b', 'c'], dtype='object')

In [48]:
# Index不可修改，这样更安全
# index[1] = 'd'  # 会报错

# 从数组创建Index
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [50]:
obj2.index is labels

True

In [51]:
# Index像固定大小的集合
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [52]:
'Ohio' in frame3.columns

True

In [53]:
2003 in frame3.index

False

In [54]:
# Index可以有重复标签
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 第2章：基本功能

### 2.1 重新索引

In [55]:
# reindex创建新对象，数据按新索引排列
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [56]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [57]:
# method参数处理缺失值，ffill向前填充
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [58]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
# DataFrame的reindex
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [61]:
# 重新索引列
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 2.2 丢弃指定轴上的项

In [62]:
# drop方法返回新对象
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [63]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [64]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [65]:
# DataFrame可以删除任意轴上的索引
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [67]:
# 删除列，指定axis=1或axis='columns'
data.drop('two', axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [68]:
data.drop(['two', 'four'], axis='columns')

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [69]:
# inplace参数原地修改（注意：这会销毁被删除的数据）
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 2.3 索引、选取和过滤

In [70]:
# Series索引
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [71]:
obj['b']

np.float64(1.0)

In [72]:
obj[1]

C:\Users\48769\AppData\Local\Temp\ipykernel_46384\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [73]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [74]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [75]:
obj[[1, 3]]

C:\Users\48769\AppData\Local\Temp\ipykernel_46384\2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [76]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [77]:
# 使用标签切片，注意包含末端
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [78]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [79]:
# DataFrame索引
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [81]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [82]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [83]:
data[data['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [85]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 2.4 用loc和iloc进行选取

In [86]:
# loc：轴标签索引
# iloc：整数索引
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
# 选取单行和多列
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [88]:
# 用iloc和整数进行选取
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [89]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [90]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [91]:
# 切片
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [92]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### 2.5 算术运算和数据对齐

In [93]:
# 自动对齐索引
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [94]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [95]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [96]:
# DataFrame对齐
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [97]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [98]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [99]:
# 填充值
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [100]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [101]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [102]:
# 使用add方法并指定fill_value
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [103]:
# DataFrame和Series之间的运算
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [104]:
arr[0]

array([0., 1., 2., 3.])

In [105]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [106]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [107]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [108]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

### 2.6 函数应用和映射

In [109]:
# NumPy的ufunc也可用于pandas对象
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

               b         d         e
Utah    0.627442  0.397744 -0.584019
Ohio    0.044336  0.821740  1.542654
Texas  -0.064082  0.945849 -0.253129
Oregon -1.537132 -0.539911  1.122222

In [110]:
np.abs(frame)

               b         d         e
Utah    0.627442  0.397744  0.584019
Ohio    0.044336  0.821740  1.542654
Texas   0.064082  0.945849  0.253129
Oregon  1.537132  0.539911  1.122222

In [111]:
# apply方法将函数应用到各行或各列
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.164574
d    1.485759
e    2.126673
dtype: float64

In [112]:
frame.apply(f, axis='columns')

Utah      1.211461
Ohio      1.498318
Texas     1.198978
Oregon    2.659355
dtype: float64

In [113]:
# 可以返回Series
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

            b         d         e
min -1.537132 -0.539911 -0.584019
max  0.627442  0.945849  1.542654

In [114]:
# applymap：元素级函数
format = lambda x: '%.2f' % x
frame.applymap(format)

C:\Users\48769\AppData\Local\Temp\ipykernel_46384\2122673422.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)

            b      d      e
Utah     0.63   0.40  -0.58
Ohio     0.04   0.82   1.54
Texas   -0.06   0.95  -0.25
Oregon  -1.54  -0.54   1.12

In [115]:
# Series的map方法
frame['e'].map(format)

Utah      -0.58
Ohio       1.54
Texas     -0.25
Oregon     1.12
Name: e, dtype: object

### 2.7 排序和排名

In [116]:
# sort_index按索引排序
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [117]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [118]:
frame.sort_index(axis=1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [119]:
# 降序
frame.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [120]:
# sort_values按值排序
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [121]:
# NaN会排到末尾
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [122]:
# DataFrame按列排序
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [123]:
frame.sort_values(by='b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [124]:
# 按多个列排序
frame.sort_values(by=['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [125]:
# rank排名
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [126]:
# 按值在原数据中出现的顺序排名
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [127]:
# 降序排名
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [128]:
# DataFrame在行或列上计算排名
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [129]:
frame.rank(axis='columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 2.8 带有重复标签的轴索引

In [130]:
# 索引标签可以重复
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [131]:
# is_unique检查是否唯一
obj.index.is_unique

False

In [132]:
# 重复标签索引返回Series
obj['a']

a    0
a    1
dtype: int64

In [133]:
obj['c']

np.int64(4)

In [134]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

          0         1         2
a  0.255493 -1.063343 -1.581196
a -0.781855 -1.040878  0.256263
b  1.350450  0.391682  1.051961
b  0.120916 -1.046893  0.254061

In [135]:
df.loc['a']

          0         1         2
a  0.255493 -1.063343 -1.581196
a -0.781855 -1.040878  0.256263

## 第3章：汇总和计算描述统计

In [136]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [137]:
# sum求和，默认按列
df.sum()

one    9.25
two   -5.80
dtype: float64

In [138]:
# 按行求和
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [139]:
# skipna参数：是否排除NaN，默认True
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [140]:
# idxmax和idxmin返回间接统计（达到最大值或最小值的索引）
df.idxmax()

one    b
two    d
dtype: object

In [141]:
# 累加
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [142]:
# describe产生多个汇总统计
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [143]:
# 非数值型数据的describe
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 第4章：处理缺失数据

In [144]:
# pandas用NaN表示缺失数据
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [145]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [146]:
# Python的None也会被当作NaN处理
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 4.1 滤除缺失数据

In [147]:
# dropna滤除缺失数据
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [148]:
# 等价于
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [149]:
# DataFrame的dropna
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [150]:
cleaned = data.dropna()
cleaned

     0    1    2
0  1.0  6.5  3.0

In [151]:
# how='all'只丢弃全为NaN的行
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [152]:
# 丢弃列，axis=1
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [153]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

### 4.2 填充缺失数据

In [154]:
# fillna填充缺失数据
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0 -0.273360       NaN       NaN
1  1.497661       NaN       NaN
2 -0.258479       NaN -0.728706
3  0.204939       NaN -0.259550
4  0.484560 -0.338686  0.536571
5  0.265652  1.625365  0.439707
6  0.296898 -0.817242 -0.856661

In [155]:
df.fillna(0)

          0         1         2
0 -0.273360  0.000000  0.000000
1  1.497661  0.000000  0.000000
2 -0.258479  0.000000 -0.728706
3  0.204939  0.000000 -0.259550
4  0.484560 -0.338686  0.536571
5  0.265652  1.625365  0.439707
6  0.296898 -0.817242 -0.856661

In [156]:
# 用字典对不同的列填充不同的值
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.273360  0.500000  0.000000
1  1.497661  0.500000  0.000000
2 -0.258479  0.500000 -0.728706
3  0.204939  0.500000 -0.259550
4  0.484560 -0.338686  0.536571
5  0.265652  1.625365  0.439707
6  0.296898 -0.817242 -0.856661

In [157]:
# inplace原地修改
_ = df.fillna(0, inplace=True)
df

          0         1         2
0 -0.273360  0.000000  0.000000
1  1.497661  0.000000  0.000000
2 -0.258479  0.000000 -0.728706
3  0.204939  0.000000 -0.259550
4  0.484560 -0.338686  0.536571
5  0.265652  1.625365  0.439707
6  0.296898 -0.817242 -0.856661

In [158]:
# 用前值填充（ffill）
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  0.263263 -0.801363 -0.214094
1 -2.481769  1.160824  0.515934
2  1.193356       NaN -1.029051
3  1.416035       NaN  0.478041
4  0.203159       NaN       NaN
5  0.462645       NaN       NaN

In [159]:
df.fillna(method='ffill')

C:\Users\48769\AppData\Local\Temp\ipykernel_46384\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

          0         1         2
0  0.263263 -0.801363 -0.214094
1 -2.481769  1.160824  0.515934
2  1.193356  1.160824 -1.029051
3  1.416035  1.160824  0.478041
4  0.203159  1.160824  0.478041
5  0.462645  1.160824  0.478041

In [160]:
df.fillna(method='ffill', limit=2)

C:\Users\48769\AppData\Local\Temp\ipykernel_46384\2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

          0         1         2
0  0.263263 -0.801363 -0.214094
1 -2.481769  1.160824  0.515934
2  1.193356  1.160824 -1.029051
3  1.416035  1.160824  0.478041
4  0.203159       NaN  0.478041
5  0.462645       NaN  0.478041

In [161]:
# 用均值填充
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 第5章：层次化索引

In [162]:
# 层次化索引允许在一个轴上拥有多个索引级别
data = pd.Series(np.random.randn(10),
                 index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

a  1   -0.448597
   2   -1.097407
   3    0.095190
b  1   -0.006695
   2   -0.568058
   3   -1.359376
c  1   -0.813511
   2    1.732633
d  2   -0.148809
   3    1.197681
dtype: float64

In [163]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [164]:
data['b']

1   -0.006695
2   -0.568058
3   -1.359376
dtype: float64

In [165]:
data['b':'c']

b  1   -0.006695
   2   -0.568058
   3   -1.359376
c  1   -0.813511
   2    1.732633
dtype: float64

In [166]:
data.loc[['b', 'd']]

b  1   -0.006695
   2   -0.568058
   3   -1.359376
d  2   -0.148809
   3    1.197681
dtype: float64

In [167]:
# 内层索引选取
data[:, 2]

a   -1.097407
b   -0.568058
c    1.732633
d   -0.148809
dtype: float64

In [168]:
# unstack将层次化索引重排为DataFrame
data.unstack()

          1         2         3
a -0.448597 -1.097407  0.095190
b -0.006695 -0.568058 -1.359376
c -0.813511  1.732633       NaN
d       NaN -0.148809  1.197681

In [169]:
# stack是unstack的逆运算
data.unstack().stack()

a  1   -0.448597
   2   -1.097407
   3    0.095190
b  1   -0.006695
   2   -0.568058
   3   -1.359376
c  1   -0.813511
   2    1.732633
d  2   -0.148809
   3    1.197681
dtype: float64

In [170]:
# DataFrame的层次化索引
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [171]:
# 索引和列都可以命名
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [172]:
# 选取列分组
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

## 补充：实际数据处理示例

In [173]:
# 模拟股票数据，计算相关系数和协方差
np.random.seed(42)
dates = pd.date_range('2023-01-01', periods=100)

# 模拟3只股票的收益率
returns = pd.DataFrame({
    'AAPL': np.random.normal(0.001, 0.02, 100),
    'GOOG': np.random.normal(0.0015, 0.025, 100),
    'MSFT': np.random.normal(0.0008, 0.018, 100)
}, index=dates)

returns.head()

                AAPL      GOOG      MSFT
2023-01-01  0.010934 -0.033884  0.007240
2023-01-02 -0.001765 -0.009016  0.010894
2023-01-03  0.013954 -0.007068  0.020295
2023-01-04  0.031461 -0.018557  0.019768
2023-01-05 -0.003683 -0.002532 -0.023998

In [174]:
# 计算累计收益率
cumulative = (1 + returns).cumprod()
cumulative.head()

                AAPL      GOOG      MSFT
2023-01-01  1.010934  0.966116  1.007240
2023-01-02  1.009150  0.957405  1.018213
2023-01-03  1.023231  0.950638  1.038878
2023-01-04  1.055423  0.932997  1.059415
2023-01-05  1.051535  0.930635  1.033991

In [175]:
# 相关系数矩阵
returns.corr()

          AAPL      GOOG      MSFT
AAPL  1.000000 -0.136422  0.190840
GOOG -0.136422  1.000000 -0.036632
MSFT  0.190840 -0.036632  1.000000

In [176]:
# 协方差矩阵
returns.cov()

          AAPL      GOOG      MSFT
AAPL  0.000330 -0.000059  0.000068
GOOG -0.000059  0.000568 -0.000017
MSFT  0.000068 -0.000017  0.000381

In [177]:
# 计算移动平均（20日）
returns_ma = returns.rolling(window=20).mean()
returns_ma.tail()

                AAPL      GOOG      MSFT
2023-04-06 -0.001913  0.003460  0.000716
2023-04-07 -0.001704  0.002339  0.001346
2023-04-08 -0.001144  0.000714  0.002163
2023-04-09 -0.001230  0.001118  0.002832
2023-04-10  0.000523 -0.003711  0.003745

In [178]:
# 统计描述
returns.describe()

             AAPL        GOOG        MSFT
count  100.000000  100.000000  100.000000
mean    -0.001077    0.002058    0.001968
std      0.018163    0.023842    0.019517
min     -0.051395   -0.046469   -0.057543
25%     -0.011018   -0.018642   -0.010998
50%     -0.001539    0.003603    0.002559
75%      0.009119    0.014954    0.013480
max      0.038046    0.069504    0.070149